version: "3.1"

networks:
  workernet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "20.3.0.1/24"
          gateway: "20.3.0.1"
  default:
    driver: bridge

services:
  db:
    name: express-boilerplate-db
    image: postgres
    restart: always
    networks:
      workernet:
        ipv4_address: 20.3.0.6
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - .:/usr/express-boilerplate/

  api:
    name: express-boilerplate-api
    image: node
    restart: always
    env_file: .env
    networks:
      workernet:
        ipv4_address: 20.3.0.7
    ports:
      - ${{ SERVER_PORT }}:${{ SERVER_PORT }}
    volumes:
      - .:/usr/express-boilerplate/
      - /usr/express-boilerplate/node_modules
    working_dir: /usr/express-boilerplate
    command: yarn prod
